/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.information.system;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author maraa
 */
public class StudentRegister extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolTitle = new javax.swing.JLabel();
        birthMonthChoice = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        studentRegisterLabel = new javax.swing.JLabel();
        birthDayChoice = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        birthYearChoice = new javax.swing.JComboBox<>();
        lastNameField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        middleNameField = new javax.swing.JTextField();
        contactNumLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        contactNumField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        submitInfoButton = new javax.swing.JButton();
        birthdateLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        gradeChoice = new javax.swing.JComboBox<>();
        sectionLabel = new javax.swing.JLabel();
        sectionChoice = new javax.swing.JComboBox<>();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        schoolTitle.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        schoolTitle.setText("XY Senior High School");

        birthMonthChoice.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        birthMonthChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        birthMonthChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthMonthChoiceActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        studentRegisterLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        studentRegisterLabel.setText("Student Registration");

        birthDayChoice.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        birthDayChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        birthDayChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthDayChoiceActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        birthYearChoice.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        birthYearChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        birthYearChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthYearChoiceActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        addressLabel.setText("Address");

        contactNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel.setText("Contact Number");

        lastNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lastNameLabel.setText("Last Name");

        firstNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        firstNameLabel.setText("First Name");

        emailLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        middleNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        middleNameLabel.setText("Middle Name");

        submitInfoButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        submitInfoButton.setText("Submit");
        submitInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitInfoButtonActionPerformed(evt);
            }
        });

        birthdateLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birthdateLabel.setText("Birthdate");

        gradeLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gradeLabel.setText("Grade");

        gradeChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));

        sectionLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        sectionLabel.setText("Section");

        sectionChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Symmetry", "Python", "Java", "Unity" }));

        passwordLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(schoolTitle)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(studentRegisterLabel)
                        .addGap(288, 288, 288))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdateLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(birthMonthChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthDayChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthYearChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addComponent(addressField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameLabel))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameLabel))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(middleNameLabel)
                                    .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactNumLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(contactNumField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailLabel)
                                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gradeLabel)
                                            .addComponent(gradeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sectionLabel)
                                            .addComponent(sectionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submitInfoButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(backButton)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(schoolTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentRegisterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(middleNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(birthdateLabel)
                                            .addComponent(addressLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(birthMonthChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birthDayChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birthYearChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gradeLabel)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sectionLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sectionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(gradeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLabel)
                                    .addComponent(emailLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitInfoButton)
                            .addComponent(backButton))))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void birthMonthChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthMonthChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthMonthChoiceActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentLogin().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void birthDayChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthDayChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDayChoiceActionPerformed

    private void birthYearChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthYearChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthYearChoiceActionPerformed

    private void submitInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitInfoButtonActionPerformed
        String lastName = lastNameField.getText();
        String firstName = firstNameField.getText();
        String middleName = middleNameField.getText();
        
        
        Date birthDate = new Date(birthYearChoice.getSelectedIndex() + 80,
                                  birthMonthChoice.getSelectedIndex(),
                                  birthDayChoice.getSelectedIndex() + 1);
        
        String address = addressField.getText();
        String contactNum = contactNumField.getText();
        String emailAddress = emailField.getText();
        String passwordInput = new String (passwordField.getPassword());
        String section = sectionChoice.getSelectedItem().toString();
        String gradeString = gradeChoice.getSelectedItem().toString();
        int gradeNew = Integer.parseInt(gradeString);
        
        if (lastName.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Last name cannot be blank.");
            return;
        }
        if (firstName.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "First name cannot be blank.");
            return;
        }
        if (middleName.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Middle name cannot be blank.");
            return;
        }
        if (address.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Address cannot be blank.");
            return;
        }
        if (contactNum.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Contact Number cannot be blank.");
            return;
        }
        if (emailAddress.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Email Address cannot be blank.");
            return;
        }
        if (passwordInput.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Password cannot be blank.");
            return;
        }
        
        DataHandler.Students.createStudent(lastName, firstName, middleName, birthDate, address, contactNum, emailAddress, gradeNew, section, passwordInput);
        
        this.setVisible(false);
        new StudentLogin().setVisible(true);
    }//GEN-LAST:event_submitInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> birthDayChoice;
    private javax.swing.JComboBox<String> birthMonthChoice;
    private javax.swing.JComboBox<String> birthYearChoice;
    private javax.swing.JLabel birthdateLabel;
    private javax.swing.JTextField contactNumField;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JComboBox<String> gradeChoice;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel schoolTitle;
    private javax.swing.JComboBox<String> sectionChoice;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel studentRegisterLabel;
    private javax.swing.JButton submitInfoButton;
    // End of variables declaration//GEN-END:variables
}
